/**
 * The drawer in the side table, as rules.
 *
 * Five pins. Each one has a point along the track where it gives, you cannot
 * see where that is, and the only thing you get is how much tension is coming
 * back — which rises as the pick nears the point. Finding it is feel, and
 * setting it is a press.
 *
 * What this file exists to guarantee is that the feel is honest. Two things
 * would make it dishonest and neither would ever be reported as a bug:
 *
 *   - a pin whose point sits so close to the edge that the tolerance runs off
 *     the end of the track is a pin you set by pushing the pick to the stop,
 *     which is not picking a lock, it is finding the corner of a box;
 *   - tension that is not strictly higher nearer the point is tension that
 *     lies, and a player following it correctly would be walking away from
 *     the answer.
 *
 * Both are checked in scripts/check-lockpick.ts against thousands of locks.
 */

/** The track the pick moves along. Arbitrary units; the UI scales them. */
export const TRACK = 100;

/** How many pins a drawer has. Five is a lock; three is a formality. */
export const PINS = 5;

/** How close counts as set. Wide enough to be findable by feel, narrow enough
 *  that sweeping the track and mashing the button does not work. */
export const TOLERANCE = 5;

/**
 * Pins must not sit on top of each other.
 *
 * Two points within a tolerance of each other means one press can set either,
 * which makes the lock feel like it is not counting properly. The gap is three
 * tolerances, so even the tension curves barely overlap.
 */
export const MIN_GAP = TOLERANCE * 3;

/** How far out tension is felt at all. Beyond this the pick is cold. */
export const FEEL = 26;

/** Slips before the lock rebinds and every pin drops. Not a permanent lock:
 *  it is a drawer in somebody's bedroom, not a safe. */
export const SLIPS_ALLOWED = 3;

/**
 * Where the pins give.
 *
 * Kept inside the track by a full tolerance at each end, so no pin can be set
 * by driving the pick to the stop, and spaced by MIN_GAP so no press can set
 * two. Generated by retry rather than by construction because five points in
 * a hundred units with a fifteen-unit gap is a loose constraint — this lands
 * inside a handful of attempts — and the retry is obviously correct where a
 * closed form would need its own proof.
 */
export function makePins(
  count: number = PINS,
  rnd: () => number = Math.random,
): number[] {
  const low = TOLERANCE;
  const high = TRACK - TOLERANCE;

  for (let attempt = 0; attempt < 500; attempt++) {
    const spots: number[] = [];
    for (let i = 0; i < count; i++) {
      spots.push(low + rnd() * (high - low));
    }
    spots.sort((a, b) => a - b);

    let ok = true;
    for (let i = 1; i < spots.length; i++) {
      if (spots[i] - spots[i - 1] < MIN_GAP) {
        ok = false;
        break;
      }
    }
    if (ok) return spots.map((s) => Math.round(s));
  }

  // Never reached with the numbers above, and a deterministic fallback is
  // better than a loop that might not terminate: evenly spaced is a valid
  // lock, just a duller one.
  const step = (high - low) / Math.max(1, count - 1);
  return Array.from({ length: count }, (_, i) => Math.round(low + i * step));
}

/** Is the pick close enough to set this pin? */
export function isSet(pick: number, spot: number): boolean {
  return Math.abs(pick - spot) <= TOLERANCE;
}

/**
 * How much the pin is giving, from 0 to 1.
 *
 * Strictly increasing as the pick nears the point, because this number IS the
 * feedback — a plateau would be a region where moving tells the player
 * nothing, and a dip would send somebody following it the wrong way.
 */
export function tensionAt(pick: number, spot: number): number {
  const away = Math.abs(pick - spot);
  if (away >= FEEL) return 0;
  return 1 - away / FEEL;
}
