/**
 * The patch panel, as rules.
 *
 * Terminals down the left, terminals down the right, and the pairs that belong
 * together are scrambled. Click one end, click the other; a matched pair stays
 * lit, a mismatch buzzes and clears.
 *
 * What this file guarantees is that the panel is always solvable and never
 * trivially so. Three ways that fails, none of which would be reported as a
 * bug:
 *
 *   - a colour appearing twice on one side, so two wires are indistinguishable
 *     and a correct answer can be marked wrong;
 *   - a side missing a colour the other side has, which is a terminal with no
 *     partner;
 *   - the right side coming out in the same order as the left, which is a
 *     panel already patched.
 */

/** The strands. Six is enough to be a job and few enough to stay legible on a
 *  phone; the names are what a screen reader announces, so they have to be
 *  words rather than hex. */
export const STRANDS = [
  { id: "red", name: "Red", hex: "#e2564a" },
  { id: "amber", name: "Amber", hex: "#e0a33c" },
  { id: "green", name: "Green", hex: "#4fb477" },
  { id: "blue", name: "Blue", hex: "#4a86d8" },
  { id: "violet", name: "Violet", hex: "#9a6fd0" },
  { id: "white", name: "White", hex: "#dcd6c6" },
] as const;

export type StrandId = (typeof STRANDS)[number]["id"];

export const strandById = (id: string) => STRANDS.find((s) => s.id === id);

/** How many strands a panel uses. All of them. */
export const PANEL_SIZE = STRANDS.length;

/* ---------------------------------------------------------------------------
   Where the terminals stand

   Here rather than in the component because the panel is dragged: a dropped
   cable end goes to the NEAREST socket within `SNAP`, so if two sockets are
   ever closer together than that, a drop lands somewhere the player did not
   aim and the panel reads as broken rather than as missed. That is an
   arithmetic relationship between four numbers, and arithmetic between numbers
   can be checked — see scripts/check-office.ts.
   ------------------------------------------------------------------------- */

/** The panel's own coordinates. The SVG is scaled to whatever width it gets. */
export const PANEL_W = 440;
export const PANEL_H = 300;
export const LEFT_X = 104;
export const RIGHT_X = PANEL_W - 104;
const TOP = 34;
/** The gap between one socket and the next. */
export const ROW = (PANEL_H - TOP * 2) / (PANEL_SIZE - 1);
export const rowY = (i: number) => TOP + i * ROW;

/** How close a dropped end has to be to count as in the socket. Generous:
 *  this is a fiddly job, not a precision one. */
export const SNAP = 34;

export type Panel = {
  /** Top to bottom on the left. */
  left: StrandId[];
  /** Top to bottom on the right. */
  right: StrandId[];
};

/**
 * A panel: the same set of strands down both sides, in different orders.
 *
 * Shuffled and then checked for being already patched rather than generated by
 * a derangement, because "no strand at the same height on both sides" is too
 * strong — a panel where nothing lines up is a different and slightly unfair
 * puzzle, and one or two that happen to line up is a real patch panel. What is
 * ruled out is only the case where EVERY strand lines up, which is a panel
 * with nothing to do.
 */
export function makePanel(rnd: () => number = Math.random): Panel {
  const left = STRANDS.map((s) => s.id as StrandId);

  const shuffle = (items: StrandId[]) => {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
      const j = Math.floor(rnd() * (i + 1));
      [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
  };

  // Both sides are shuffled BEFORE they are compared, and the comparison is
  // between the two arrays that are actually returned. Checking the shuffled
  // right against the unshuffled left — which is what this did — tests the
  // wrong pair entirely, and lets a panel out that is already patched.
  const a = shuffle(left);
  let b = shuffle(left);
  // An identity is a panel with nothing to do. Rotating by one cannot be an
  // identity, so a single repair is enough.
  if (b.every((id, i) => id === a[i])) {
    b = [...b.slice(1), b[0]];
  }
  return { left: a, right: b };
}

/** Two ends belong together when they are the same strand. */
export function joins(a: StrandId, b: StrandId): boolean {
  return a === b;
}

/** Every strand patched. */
export function isPatched(panel: Panel, made: StrandId[]): boolean {
  return panel.left.every((id) => made.includes(id));
}
